In [1]:
%pip install -Uq numpy

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.57.1 requires numpy<1.25,>=1.21, but you have numpy 1.26.0 which is incompatible.

[notice] A new release of pip is available: 23.0 -> 23.2.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [30]:
npmatrix1 = np.array([
    [1, 1, 1],
    [1, 2, 3],
    [11, 12, 13],
    [11, 22, 33],
])

npmatrix2 = np.array([
    [4, 5, 6],
    [7, 8, 9],
    [77, 12, 12],
    [2, 1, 45],
])

In [31]:
npmatrix1 * npmatrix2

array([[   4,    5,    6],
       [   7,   16,   27],
       [ 847,  144,  156],
       [  22,   22, 1485]])

In [32]:
npmatrix1 * 2

array([[ 2,  2,  2],
       [ 2,  4,  6],
       [22, 24, 26],
       [22, 44, 66]])

In [33]:
npmatrix1 @ npmatrix2.T  # T()

array([[  15,   24,  101,   48],
       [  32,   50,  137,  139],
       [ 182,  290, 1147,  619],
       [ 352,  550, 1507, 1529]])

In [34]:
npmatrix2 / 2

array([[ 2. ,  2.5,  3. ],
       [ 3.5,  4. ,  4.5],
       [38.5,  6. ,  6. ],
       [ 1. ,  0.5, 22.5]])

In [35]:
npmatrix2 - npmatrix1

array([[  3,   4,   5],
       [  6,   6,   6],
       [ 66,   0,  -1],
       [ -9, -21,  12]])

In [36]:
npmatrix1 + npmatrix2

array([[ 5,  6,  7],
       [ 8, 10, 12],
       [88, 24, 25],
       [13, 23, 78]])

In [37]:
npmatrix1 @ npmatrix2.T

array([[  15,   24,  101,   48],
       [  32,   50,  137,  139],
       [ 182,  290, 1147,  619],
       [ 352,  550, 1507, 1529]])

## ЭТО НЕ ДЛЯ ВАС, ЭТО ДЛЯ МЕНЯ НА ВРЕМЯ РАБОТЫ НАД ТЕСТОМ

То, что вам нужно - в последних двух клеточках.

In [120]:
# BASE DUMMY CLASS FOR `isinstance` TO WORK
class BaseMatrix:
    pass

# DUMMY CLASS
class Matrix(BaseMatrix):
    matrix = np.array([])
    
    def T(self):
        transposed_matrix = Matrix()
        transposed_matrix.matrix = self.matrix.T
        return transposed_matrix
    
    # len(matrix1)
    def __len__(self):
        return len(self.matrix)
    
    # +
    def __add__(self, other):
        if isinstance(other, BaseMatrix):
            return self.matrix + other.matrix
        elif isinstance(other, (int, float)):
            return self.matrix + other
    
    # -
    def __sub__(self, other):
        if isinstance(other, BaseMatrix):
            return self.matrix - other.matrix
        elif isinstance(other, (int, float)):
            return self.matrix - other
    
    # *
    def __mul__(self, other):
        if isinstance(other, BaseMatrix):
            return self.matrix * other.matrix
        elif isinstance(other, (int, float)):
            return self.matrix * other
    
    # /
    def __truediv__(self, other):
        if isinstance(other, BaseMatrix):
            return self.matrix / other.matrix
        elif isinstance(other, (int, float)):
            return self.matrix / other
    
    # @
    def __matmul__(self, other):
        if isinstance(other, BaseMatrix):
            return self.matrix @ other.matrix
        elif isinstance(other, (int, float)):
            return self.matrix @ other
    
    # ==
    def __eq__(self, other):
        if isinstance(other, BaseMatrix):
            return self.matrix == other.matrix
        elif isinstance(other, np.ndarray):
            return self.matrix == other
        
    def __repr__(self):
        return str(self.matrix)
    
    
matrix1 = Matrix()
matrix2 = Matrix()

matrix1.matrix = npmatrix1
matrix2.matrix = npmatrix2

In [122]:
class Test:
    array = [[1, 2, 3], [1, 2, 3]]
    
    def __repr__(self):
        return str(self.array)
    
t = Test()
t

[[1, 2, 3], [1, 2, 3]]

In [119]:
str(matrix1)

TypeError: sequence item 0: expected str instance, numpy.ndarray found

## ЭТО ТО ЧТО ВАМ НУЖНО

Скопируйте обе клеточки и запустите, дополнительно модифицировав вторую. Я укажу где.

In [103]:
%pip install -q ipytest pytest

import ipytest
import pytest
ipytest.autoconfig()


[notice] A new release of pip is available: 23.0 -> 23.2.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


## ТО ЧТО ВАМ НУЖНО

Измените `matrix1` и `matrix2` заменив на ваши классы с вашими любыми числами и запустите. Должны пройти абсолютно все тесты.

In [108]:
%%ipytest

#matrix1 = Matrix([...some_array...])
#matrix2 = Matrix([...some_array...])

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_add_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (matrix1 + matrix2 == (np.array(matrix1.matrix) + np.array(matrix2.matrix))).all()
    ), 'add section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 13.2]])
def test_matrix_add_number(matrix1: Matrix, number: int | float):
    assert (
        (matrix1 + number == np.array(matrix1.matrix) + number).all()
    ), 'add section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_sub_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (matrix1 - matrix2 == np.array(matrix1.matrix) - np.array(matrix2.matrix)).all()
    ), 'sub section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 12.2]])    
def test_matrix_sub_number(matrix1: Matrix, number: int | float):
    assert (
        (matrix1 - number == np.array(matrix1.matrix) - number).all()
    ), 'sub section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1", [matrix1])    
def test_matrix_transpose(matrix1: Matrix):
    assert (
        (matrix1.T() == np.array(matrix1.matrix).T).all()
    ), 'transpose section is not working right'
    
# -----------------------------------------

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_mul_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (matrix1 * matrix2 == np.array(matrix1.matrix) * np.array(matrix2.matrix)).all()
    ), 'mul section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 13]])
def test_matrix_mul_number(matrix1: Matrix, number: int | float):
    assert (
        (matrix1 * number == np.array(matrix1.matrix) * number).all()
    ), 'mul section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])    
def test_matrix_div_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (matrix1 / matrix2 == np.array(matrix1.matrix) / np.array(matrix2.matrix)).all()
    ), 'div section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 2]])    
def test_matrix_div_number(matrix1: Matrix, number: int | float):
    assert (
        (matrix1 / number == np.array(matrix1.matrix) / number).all()
    ), 'div section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2.T()]])    
def test_matrix_matmul_matrix(matrix1: Matrix, matrix2: Matrix):
    assert(
        (matrix1 @ matrix2 == np.array(matrix1.matrix) @ np.array(matrix2.matrix)).all()
    ), 'matmul section is not working right, and don\'t forget about T() if needed'
    
    


..........                                                                                   [100%]
10 passed in 0.01s
